#!/bin/bash
# shellcheck shell=bash
#=======================================================================
# ohos-kernel-port / scripts/lib/config.sh
#
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026 ohos-kernel-port contributors
# SPDX-License-Identifier: GPL-2.0-only
#
# Kernel configuration.
#
# WHY kernel_linux_config IS MANDATORY  (measured 2026-10-04)
# -------------------------------------------------------
# It is tempting to assume the OpenHarmony kernel tree ships its own OHOS
# defconfig and that arch/<arch>/configs/defconfig can be used directly.
# Measured on kernel_linux_6.6 @ OpenHarmony-7.0-Release (commit f4b61510):
#
#     in-tree arch/arm64/configs/defconfig     1579 CONFIG symbols
#     kernel_linux_config base_defconfig          43 CONFIG symbols
#     kernel_linux_config type/standard_defconfig 755 CONFIG symbols
#     union of the two config-repo layers         798 CONFIG symbols
#     of those, present in the in-tree defconfig  110  (13 %)
#
# 652 symbols that OpenHarmony actually configures are absent from the in-tree
# defconfig, including CONFIG_ACCESS_TOKENID, CONFIG_ANDROID_BINDER_IPC and the
# CONFIG_ANDROID family.  A kernel built from the in-tree defconfig is
# therefore NOT an OpenHarmony kernel.  config.sh deliberately treats the
# config repo as the source of truth and logs which layer supplied the base,
# so a regression here cannot pass silently.
#
# LAYER ORDER (later layers win)
#   1. kernel_linux_config  linux-<ver>/base_defconfig        (OHOS repo)
#   2. kernel_linux_config  linux-<ver>/type/<type>_defconfig (OHOS repo)
#      ...or a complete per-board config, which supersedes 1+2 entirely
#   3. in-tree              arch/<arch>/configs/defconfig      (fallback only)
#   4. configs/base/<arch>/*.config                            (this repo)
#   5. configs/lanes/<overlay>/*.config                         (this repo)
#   6. --config PATH (adhoc, not persisted)
#   7. make olddefconfig                                        (re-derive)
#=======================================================================

[[ -n "${_OKCP_CONFIG_SH:-}" ]] && return 0
_OKCP_CONFIG_SH=1
# shellcheck source=./common.sh
[[ -z "${OKCP_ROOT:-}" ]] && source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"
# shellcheck source=./matrix.sh
[[ -z "${_OKCP_MATRIX_SH:-}" ]] && source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/matrix.sh"

OKCP_CONFIG_ROOT="${OKCP_ROOT}/configs"
OKCP_CONFIG_REPO="${OKCP_CONFIG_REPO:-kernel_linux_config}"
OKCP_OHOS_HOST="${OKCP_OHOS_HOST:-https://gitcode.com/openharmony}"

# System type: standard (full OHOS standard system) | small (lightweight/IoT).
# Mirrors kernel_linux_config/linux-<ver>/type/.
OKCP_SYSTEM_TYPE="${OKCP_SYSTEM_TYPE:-standard}"
# Board directory inside kernel_linux_config (rk3568, qemu, ...).  Empty means
# no board layer.
OKCP_BOARD="${OKCP_BOARD:-}"

#-------------------------------------------------------------------- arch
config_arch() {
    local lane=$1
    if [[ -n "${OKCP_ARCH:-}" ]]; then printf '%s\n' "${OKCP_ARCH}"; return 0; fi
    case "$(lane_repo "${lane}")" in
        kernel_linux_4.19|kernel_linux) printf 'arm\n' ;;
        *) printf 'arm64\n' ;;
    esac
}

#------------------------------------------------------- config repo access
fetch_ohos_config_repo() {
    local lane=$1 dest=${2:-${OKCP_WORKDIR:-${OKCP_ROOT}/build}/config/${lane}}
    local branch url
    branch=$(lane_ohos_branch "${lane}")
    [[ "${branch}" != "-" ]] || die "lane '${lane}' is not an OpenHarmony lane; it has no config-repo branch"
    url="${OKCP_OHOS_HOST}/${OKCP_CONFIG_REPO}.git"

    if [[ -d "${dest}/.git" ]]; then printf '%s\n' "${dest}"; return 0; fi
    mkdir -p "$(dirname -- "${dest}")"
    log_step "fetching OpenHarmony config repo: ${OKCP_CONFIG_REPO}@${branch}"
    retry "${OKCP_FETCH_ATTEMPTS:-10}" "${OKCP_FETCH_BACKOFF:-30}" \
        git_do clone --depth=1 --single-branch --branch "${branch}" "${url}" "${dest}" \
        || die "cannot fetch ${url} (branch ${branch})"
    printf '%s\n' "${dest}"
}

# Is a defconfig a complete generated .config rather than a fragment?
config_is_full() {
    local f=$1 lines
    [[ -f "${f}" ]] || return 1
    lines=$(wc -l < "${f}" 2>/dev/null || echo 0)
    head -20 "${f}" | grep -qiE 'Automatically generated file|Generated by' && return 0
    (( lines > 2000 ))
}

# Fragments from this repository, in application order.
collect_local_fragments() {
    local lane=$1 arch=$2 d
    for d in "${OKCP_CONFIG_ROOT}/base/${arch}" "${OKCP_CONFIG_ROOT}/lanes/$(lane_overlay "${lane}")"; do
        if [[ -d "${d}" ]]; then
            find "${d}" -maxdepth 1 -type f \( -name '*.config' -o -name '*.fragment' \) | sort
        else
            log_debug "no config layer: ${d}"
        fi
    done
}

#--------------------------------------------------------------- merging
# _merge_fragments <srcdir> <out_config> <fragment>...
#
# Delegates to the kernel's own scripts/kconfig/merge_config.sh so we inherit
# upstream's handling of overridden and redundant symbols instead of
# reimplementing it.
#
# Its real contract, read from Linux 6.6.101 scripts/kconfig/merge_config.sh:
#
#   -m              boolean: merge only, do not run make afterwards
#   -O <dir>        directory for the generated output; the result is
#                   <dir>/.config  (it sets KCONFIG_CONFIG accordingly)
#   <base> <frags>  the first positional is the BASE file, the rest are
#                   fragments merged over it, later definitions winning
#
# There is no "-m <file>".  An earlier version of this function passed one,
# which made the real script treat the output path as a fragment and leave the
# real result in the -O directory; a stub that mirrored the invented contract
# hid the bug until CI met the real one.
#
# The script creates its temporary files in the current directory, so it must
# run with the kernel source tree as cwd.
_merge_fragments() {
    local srcdir=$1 out=$2; shift 2
    local -a frags=()
    local f
    for f in "$@"; do
        if [[ -s "${f}" ]]; then frags+=("${f}"); fi
    done
    if [[ ${#frags[@]} -eq 0 ]]; then
        die "no config fragments to merge"
    fi

    local merge="${srcdir}/scripts/kconfig/merge_config.sh"
    if [[ ! -x "${merge}" ]]; then
        die "${merge} not found or not executable; cannot merge config fragments"
    fi

    local tmp; tmp=$(make_tmpdir)
    : > "${tmp}/base.config"          # an empty base keeps ordering explicit

    # -m and -O must stay in this order-free form: the real script consumes -m
    # as a flag and -O as an argument, so nothing may be glued together.
    if ! ( cd "${srcdir}" && bash "${merge}" -m -O "${tmp}" "${tmp}/base.config" "${frags[@]}" ); then
        log_warn "merge_config.sh exited non-zero (continuing; olddefconfig will settle it)"
    fi

    if [[ ! -s "${tmp}/.config" ]]; then
        log_error "config merge produced no ${tmp}/.config"
        log_error "  fragments: $(printf '%s ' ${frags[@]+"${frags[@]}"})"
        log_error "  merge script: ${merge}"
        rm -rf "${tmp}"
        die "cannot merge the OpenHarmony configuration fragments"
    fi

    cp "${tmp}/.config" "${out}"
    rm -rf "${tmp}"
    printf '%s\n' "${out}"
}

#--------------------------------------------------------------- entry
# generate_config <lane> <srcdir> [outdir]
generate_config() {
    local lane=$1 srcdir=$2 outdir=${3:-${srcdir}}
    local out="${outdir}/.config" arch mode="fragment" base_desc=""
    local -a frags=()

    require_file "${srcdir}/Makefile"
    arch=$(config_arch "${lane}")
    mkdir -p "${outdir}"

    #-- layer 0: explicit override ---------------------------------------
    if [[ -n "${OKCP_CONFIG_OVERRIDE:-}" ]]; then
        require_file "${OKCP_CONFIG_OVERRIDE}"
        log_step "config: explicit override ${OKCP_CONFIG_OVERRIDE}"
        if config_is_full "${OKCP_CONFIG_OVERRIDE}"; then
            mode="full"; cp "${OKCP_CONFIG_OVERRIDE}" "${out}"
        else
            frags+=("${OKCP_CONFIG_OVERRIDE}")
        fi

    #-- layers 1-2: the OpenHarmony config repo -------------------------
    elif [[ "$(lane_source_kind "${lane}")" == "ohos" && -z "${OKCP_NO_OHOS_CONFIG:-}" ]]; then
        # Every one of these is initialised to the empty string on purpose.
        # Under `set -u`, `local x` with no assignment leaves x *unset*, so a
        # short-circuited `[[ cond ]] && x=...` makes any later reference fail
        # with "unbound variable" instead of simply being empty.
        local cfgroot="" series="" base_def="" type_def="" board_def=""
        series=$(kernel_series "$(lane_kver "${lane}")")
        cfgroot=$(fetch_ohos_config_repo "${lane}")

        # OpenHarmony's config repository uses two conventions.
        #
        #   modern (5.10, 6.6):
        #     linux-<s>/base_defconfig
        #     linux-<s>/type/{standard,small}_defconfig
        #     linux-<s>/<board>/arch/<arch>_defconfig        (complete)
        #
        #   legacy (4.19):  no base layer, and everything sits under arch/
        #     linux-4.19/arch/<arch>/configs/{standard,small}_common_defconfig
        #     linux-4.19/arch/<arch>/configs/<board>_<type>_defconfig
        #
        # Try the modern layout first, then the legacy one, so a lane against
        # either generation resolves.
        if [[ -f "${cfgroot}/linux-${series}/base_defconfig" \
           || -f "${cfgroot}/linux-${series}/type/${OKCP_SYSTEM_TYPE}_defconfig" ]]; then
            base_def="${cfgroot}/linux-${series}/base_defconfig"
            type_def="${cfgroot}/linux-${series}/type/${OKCP_SYSTEM_TYPE}_defconfig"
            if [[ -n "${OKCP_BOARD}" && -d "${cfgroot}/linux-${series}/${OKCP_BOARD}" ]]; then
                board_def="${cfgroot}/linux-${series}/${OKCP_BOARD}/arch/${arch}_defconfig"
            fi
        else
            local legacy="${cfgroot}/linux-${series}/arch/${arch}/configs"
            type_def="${legacy}/${OKCP_SYSTEM_TYPE}_common_defconfig"
            if [[ -n "${OKCP_BOARD}" ]]; then
                board_def="${legacy}/${OKCP_BOARD}_${OKCP_SYSTEM_TYPE}_defconfig"
            fi
        fi

        if [[ -n "${board_def}" && -f "${board_def}" ]] && config_is_full "${board_def}"; then
            log_step "config: complete OpenHarmony board config for '${OKCP_BOARD}'"
            base_desc="kernel_linux_config linux-${series}/${OKCP_BOARD} (complete)"
            mode="full"; cp "${board_def}" "${out}"
        elif [[ -f "${base_def}" || -f "${type_def}" ]]; then
            log_step "config: OpenHarmony config repo (linux-${series}, type/${OKCP_SYSTEM_TYPE})"
            [[ -f "${base_def}" ]]  && frags+=("${base_def}")
            [[ -f "${type_def}" ]]  && frags+=("${type_def}")
            [[ -f "${board_def}" ]] && frags+=("${board_def}")
            base_desc="kernel_linux_config linux-${series} (${#frags[@]} fragment(s))"
        fi
    fi

    #-- layer 3: in-tree fallback (loudly) -------------------------------
    if [[ "${mode}" == "fragment" && ${#frags[@]} -eq 0 ]]; then
        local own="${srcdir}/arch/${arch}/configs/defconfig"
        if [[ -f "${own}" ]]; then
            log_warn "the OpenHarmony config repo was not consulted; falling back to the"
            log_warn "  in-tree defconfig ${own#"${srcdir}"/}"
            log_warn "  This is NOT an OpenHarmony configuration: measured on 6.6.101 it"
            log_warn "  omits 652 of the 798 symbols OpenHarmony sets, including"
            log_warn "  CONFIG_ACCESS_TOKENID and CONFIG_ANDROID_BINDER_IPC."
            log_warn "  Pass --config, or remove --no-ohos-config, to build a real OHOS kernel."
            frags+=("${own}")
            base_desc="in-tree defconfig (FALLBACK, not an OHOS config)"
        fi
    fi

    #-- layers 4-5: this repository's overlays --------------------------
    local -a local_frags=()
    mapfile -t local_frags < <(collect_local_fragments "${lane}" "${arch}")
    if [[ ${#local_frags[@]} -gt 0 ]]; then
        log_step "config: applying ${#local_frags[@]} local fragment(s) on top"
        local f
        for f in "${local_frags[@]}"; do log_debug "  fragment: ${f#"${OKCP_ROOT}"/}"; done
        frags+=("${local_frags[@]}")
    fi

    # Nothing selected a base configuration and there is nothing to merge: that
    # is a real error.  The check must allow for the fragment path, where
    # ${out} does not exist yet because the merge below is what creates it.
    if [[ ! -f "${out}" && ${#frags[@]} -eq 0 ]]; then
        die "no base configuration was selected for lane '${lane}'
  Expected one of:
    - a complete board config in kernel_linux_config/linux-${series}/
    - kernel_linux_config/linux-${series}/{base,type/} defconfig
    - ${srcdir}/arch/${arch}/configs/defconfig
  Run './ohos-kb show ${lane}' to see what this lane resolves to."
    fi

    #-- merge -------------------------------------------------------------
    if [[ ${#frags[@]} -gt 0 ]]; then
        local tmp; tmp=$(make_tmpdir)
        _merge_fragments "${srcdir}" "${tmp}/merged" "${frags[@]}" >/dev/null
        cp "${tmp}/merged" "${out}"
        rm -rf "${tmp}"
    fi

    #-- settle ------------------------------------------------------------
    log_step "config: olddefconfig"
    make -C "${srcdir}" -s ARCH="${arch}" olddefconfig >/dev/null 2>&1 \
        || log_warn "olddefconfig exited non-zero (often benign; continuing)"
    cp -f "${out}" "${outdir}/.okcp-resolved-config" 2>/dev/null || true

    log_ok "config ready: ${out#"${OKCP_ROOT}"/} ($(wc -l < "${out}") lines)"
    log_info "base layer: ${base_desc:-adhoc override}"
    config_facts "${out}" | sed 's/^/  /' | head -20
    printf '%s\n' "${out}"
}

#-------------------------------------------------------------------- facts
# The handful of options a reader actually asks about, so a CI job summary can
# answer "was this really an OpenHarmony kernel?" without opening 40k lines.
config_facts() {
    local cfg=$1 sym
    for sym in \
        CONFIG_LOCALVERSION CONFIG_ARM64 CONFIG_MODULES CONFIG_MODULE_UNLOAD \
        CONFIG_ACCESS_TOKENID CONFIG_ANDROID CONFIG_ANDROID_BINDER_IPC \
        CONFIG_SECURITY_SELINUX CONFIG_SECCOMP CONFIG_CFI_CLANG \
        CONFIG_BPF CONFIG_DRM CONFIG_NVME_CORE CONFIG_BLK_DEV_NVME \
        CONFIG_EXT4_FS CONFIG_F2FS_FS CONFIG_EROFS_FS CONFIG_OVERLAY_FS
    do
        grep -E "^${sym}=" "${cfg}" 2>/dev/null || true
    done | sort -u
}

# Which image artefacts this config will produce.
config_image_targets() {
    local cfg=$1
    require_file "${cfg}"
    local -a t=()
    grep -qx 'CONFIG_ARM64=y' "${cfg}" 2>/dev/null && t+=(Image)
    grep -qx 'CONFIG_ARM64=y' "${cfg}" 2>/dev/null && t+=(Image.gz)
    if grep -qx 'CONFIG_EFI=y' "${cfg}" 2>/dev/null; then t+=(Image-dtb); fi
    [[ ${#t[@]} -eq 0 ]] && t=(vmlinux bzImage)
    printf '%s\n' "${t[@]}" | sort -u
}

# Fast, build-free config check used by the PR gate workflow.
config_check() {
    local lane=$1 srcdir=$2 outdir
    outdir=$(make_tmpdir)
    generate_config "${lane}" "${srcdir}" "${outdir}" >/dev/null
    log_ok "config check passed for ${lane} ($(wc -l < "${outdir}/.config") lines)"
    rm -rf "${outdir}"
}
